{ url: 'https://api.github.com/repos/CSCI-4830-002-2014/pre-class-survey/issues/35',
  labels_url: 'https://api.github.com/repos/CSCI-4830-002-2014/pre-class-survey/issues/35/labels{/name}',
  comments_url: 'https://api.github.com/repos/CSCI-4830-002-2014/pre-class-survey/issues/35/comments',
  events_url: 'https://api.github.com/repos/CSCI-4830-002-2014/pre-class-survey/issues/35/events',
  html_url: 'https://github.com/CSCI-4830-002-2014/pre-class-survey/issues/35',
  id: 43357117,
  number: 35,
  title: 'Challenge 6',
  user: 
   { login: 'Irfann1',
     id: 7736082,
     avatar_url: 'https://avatars.githubusercontent.com/u/7736082?v=2',
     gravatar_id: 'b7817f283a210fed14de936c18592beb',
     url: 'https://api.github.com/users/Irfann1',
     html_url: 'https://github.com/Irfann1',
     followers_url: 'https://api.github.com/users/Irfann1/followers',
     following_url: 'https://api.github.com/users/Irfann1/following{/other_user}',
     gists_url: 'https://api.github.com/users/Irfann1/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/Irfann1/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/Irfann1/subscriptions',
     organizations_url: 'https://api.github.com/users/Irfann1/orgs',
     repos_url: 'https://api.github.com/users/Irfann1/repos',
     events_url: 'https://api.github.com/users/Irfann1/events{/privacy}',
     received_events_url: 'https://api.github.com/users/Irfann1/received_events',
     type: 'User',
     site_admin: false },
  labels: [],
  state: 'open',
  locked: false,
  assignee: null,
  milestone: null,
  comments: 0,
  created_at: '2014-09-22T03:10:59Z',
  updated_at: '2014-09-22T03:10:59Z',
  closed_at: null,
  body: 'Test post, carry on.',
  closed_by: null }
