[ { total: 4,
    weeks: [ [Object], [Object], [Object] ],
    author: 
     { login: 'doubleshow',
       id: 129562,
       avatar_url: 'https://avatars.githubusercontent.com/u/129562?v=2',
       gravatar_id: 'fd560523056cc1f20d64b172df704748',
       url: 'https://api.github.com/users/doubleshow',
       html_url: 'https://github.com/doubleshow',
       followers_url: 'https://api.github.com/users/doubleshow/followers',
       following_url: 'https://api.github.com/users/doubleshow/following{/other_user}',
       gists_url: 'https://api.github.com/users/doubleshow/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/doubleshow/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/doubleshow/subscriptions',
       organizations_url: 'https://api.github.com/users/doubleshow/orgs',
       repos_url: 'https://api.github.com/users/doubleshow/repos',
       events_url: 'https://api.github.com/users/doubleshow/events{/privacy}',
       received_events_url: 'https://api.github.com/users/doubleshow/received_events',
       type: 'User',
       site_admin: false } },
  { total: 6,
    weeks: [ [Object], [Object], [Object] ],
    author: 
     { login: 'LoganBates',
       id: 3269358,
       avatar_url: 'https://avatars.githubusercontent.com/u/3269358?v=2',
       gravatar_id: '3b26ae9a02d2c6711989a2c56b354dac',
       url: 'https://api.github.com/users/LoganBates',
       html_url: 'https://github.com/LoganBates',
       followers_url: 'https://api.github.com/users/LoganBates/followers',
       following_url: 'https://api.github.com/users/LoganBates/following{/other_user}',
       gists_url: 'https://api.github.com/users/LoganBates/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/LoganBates/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/LoganBates/subscriptions',
       organizations_url: 'https://api.github.com/users/LoganBates/orgs',
       repos_url: 'https://api.github.com/users/LoganBates/repos',
       events_url: 'https://api.github.com/users/LoganBates/events{/privacy}',
       received_events_url: 'https://api.github.com/users/LoganBates/received_events',
       type: 'User',
       site_admin: false } } ]
